## <center> Preprocessing Methods </center>

- binarization
- scaling
- normalization
- mean removal
- etc.

### 1. Binarization

In [3]:
from sklearn import preprocessing
import numpy as np 

data = np.array([[2.2, 5.9, -1.8], [5.4, -3.2, -5.1], [-1.9, 4.2, 3.2]])

In [4]:
bindata = preprocessing.Binarizer(threshold=1.5).transform(data)
print('Binarized data:\n\n', bindata)

Binarized data:

 [[ 1.  1.  0.]
 [ 1.  0.  0.]
 [ 0.  1.  1.]]
